### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by nmaludy** [ManageIQ/manageiq-api-client-python#31]
There have been lots of improvements since the last release `v0.3.0`. Would it be possible if you cut a new release so we can realize these changes when installing from `pip`?

Thanks!

**Comment by ryankwilliams** [comment]
+1 I also am looking for some of the new changes since your last release when installing via pip.

**Comment by cben** [comment]
cc @mkoura @simon3z.  @simon3z can you merge #32 and review #29?

Hmm, seems @mkoura and me are listed as maintainers in https://pypi.python.org/pypi/manageiq-client so we should be able to do it.

**Comment by cben** [comment]
@mkoura I was hoping I'll get to it early this week, but had no time and still have no time :(
Could you make a release?

**Comment by ryankwilliams** [comment]
Thank you for releasing [0.4.0](https://pypi.python.org/pypi/manageiq-client/0.4.0)!

**Comment by cben** [comment]
@nmaludy can this be closed?

**Comment by nmaludy** [comment]
Yes, thanks!
