### ISSUE TITLE
For py3 better compatibility `map` object should not return. 

### ISSUE THREAD

**Issue by digitronik** [ManageIQ/manageiq-api-client-python#47]
I found our calls returning `map` objects. user will face problems like 
`TypeError: 'map' object is not subscriptable` while they go for indexing.

As per me its should return `list` or `tuple`. return type should not be `map` object.

In `py2` `map` object allow indexing but not in `py3`. For workaround user need list compression which is not good.

Let me know maintainers thought on it.

**Comment by cben** [comment]
~~Do you mean `dict` objects or something else?
Can you give a concrete example what returns such object?~~

**Comment by cben** [comment]
Aah, got it, that's what #48 was for.  In py 3 `map()` returns a lazy iterator object.
