### ISSUE TITLE
Correct escaping of find_by

### ISSUE THREAD

**Issue by mfalesni** [ManageIQ/manageiq-api-client-python#8]
https://github.com/ManageIQ/manageiq-api-client-python/blob/master/src/miqclient/api.py#L232

**Comment by cben** [comment]
If this is in relation to @dkorn's unicode troubles, turns out this line (at least for him) works fine;
his problem was in statements like `raise APIException("foo {} bar".format(something_unicode))`, he's preparing a PR for those.

**Comment by mfalesni** [comment]
@cben #9

**Comment by cben** [comment]
#9 is long merged, I believe this can closed.
